// Mocks generated by Mockito 5.4.4 from annotations
// in ttm01_flutter_dependency_injection/test/data/post_repository.impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ttm01_flutter_dependency_injection/data/models/post.model.dart'
    as _i2;
import 'package:ttm01_flutter_dependency_injection/data/post.remote.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostModel_0 extends _i1.SmartFake implements _i2.PostModel {
  _FakePostModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i3.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PostModel>> fetchAll() => (super.noSuchMethod(
        Invocation.method(
          #fetchAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.PostModel>>.value(<_i2.PostModel>[]),
      ) as _i4.Future<List<_i2.PostModel>>);

  @override
  _i4.Future<_i2.PostModel> detailPosts(int? id) => (super.noSuchMethod(
        Invocation.method(
          #detailPosts,
          [id],
        ),
        returnValue: _i4.Future<_i2.PostModel>.value(_FakePostModel_0(
          this,
          Invocation.method(
            #detailPosts,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.PostModel>);
}
